/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base-layout/index.vue"),
  blank: () => import("@/layouts/blank-layout/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  403: () => import("@/views/(builtin)/403/index.vue"),
  404: () => import("@/views/(builtin)/404/index.vue"),
  500: () => import("@/views/(builtin)/500/index.vue"),
  Home: () => import("@/views/home/index.vue"),
  IframeUrl: () => import("@/views/(builtin)/iframe/[url].vue"),
  Login: () => import("@/views/(builtin)/login/index.vue"),
  ManageMenu: () => import("@/views/manage/menu/index.vue"),
  ManageRole: () => import("@/views/manage/role/index.vue"),
  ManageRoute: () => import("@/views/manage/route/index.vue"),
  ManageUser: () => import("@/views/manage/user/index.vue"),
  Wip: () => import("@/views/(builtin)/wip/index.vue"),
};
