/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: '403',
    path: '/403',
    layout: 'base',
    component: '403',
    meta: {
      title: "403",
      constant: true
    },
  },
  {
    name: '404',
    path: '/404',
    layout: 'base',
    component: '404',
    meta: {
      title: "404",
      constant: true
    },
  },
  {
    name: '500',
    path: '/500',
    layout: 'base',
    component: '500',
    meta: {
      title: "500",
      constant: true
    },
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
    meta: {
      title: "Home"
    },
  },
  {
    name: 'IframeUrl',
    path: '/iframe/:url',
    layout: 'base',
    component: 'IframeUrl',
    meta: {
      title: "IframeUrl"
    }
  },
  {
    name: 'Login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    layout: 'base',
    component: 'Login',
    meta: {
      title: "Login",
      constant: true
    },
  },
  {
    name: 'ManageMenu',
    path: '/manage/menu',
    layout: 'base',
    component: 'ManageMenu',
    meta: {
      title: "ManageMenu"
    },
  },
  {
    name: 'ManageRole',
    path: '/manage/role',
    layout: 'base',
    component: 'ManageRole',
    meta: {
      title: "ManageRole"
    },
  },
  {
    name: 'ManageRoute',
    path: '/manage/route',
    layout: 'base',
    component: 'ManageRoute',
    meta: {
      title: "ManageRoute"
    }
  },
  {
    name: 'ManageUser',
    path: '/manage/user',
    layout: 'base',
    component: 'ManageUser',
    meta: {
      title: "ManageUser"
    },
  },
  {
    name: 'Wip',
    path: '/wip',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "Wip"
    }
  }
];
