/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteKey, RoutePathMap } from '@elegant-router/types';

const routePathMap: RoutePathMap = {
  "Root": "/",
  "NotFound": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "Home": "/home",
  "IframeUrl": "/iframe/:url",
  "Login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "ManageMenu": "/manage/menu",
  "ManageRole": "/manage/role",
  "ManageRoute": "/manage/route",
  "ManageUser": "/manage/user",
  "Wip": "/wip",
};

export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}
