// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/custom/BetterScroll.vue')['default']
    CountTo: typeof import('./src/components/custom/CountTo.vue')['default']
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/DarkModeSwitch.vue')['default']
    GithubLink: typeof import('./src/components/custom/GithubLink.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    IconSelect: typeof import('./src/components/custom/IconSelect.vue')['default']
    ImageVerify: typeof import('./src/components/custom/ImageVerify.vue')['default']
    LoadingEmptyWrapper: typeof import('./src/components/business/LoadingEmptyWrapper.vue')['default']
    LoginAgreement: typeof import('./src/components/business/LoginAgreement.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    SystemLogo: typeof import('./src/components/common/SystemLogo.vue')['default']
    WebSiteLink: typeof import('./src/components/custom/WebSiteLink.vue')['default']
  }
}

export { }
