// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/custom/BetterScroll.vue')['default'];
    CountTo: typeof import('./src/components/custom/CountTo.vue')['default'];
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default'];
    DarkModeSwitch: typeof import('./src/components/common/DarkModeSwitch.vue')['default'];
    GithubLink: typeof import('./src/components/custom/GithubLink.vue')['default'];
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default'];
    IconAntDesignCloseOutlined: typeof import('~icons/ant-design/close-outlined')['default'];
    IconAntDesignEnterOutlined: typeof import('~icons/ant-design/enter-outlined')['default'];
    IconAntDesignSettingOutlined: typeof import('~icons/ant-design/setting-outlined')['default'];
    IconCustomAvatar: typeof import('~icons/custom/avatar')['default'];
    IconCustomEmptyData: typeof import('~icons/custom/empty-data')['default'];
    IconCustomLogo: typeof import('~icons/custom/logo')['default'];
    IconCustomLogoFill: typeof import('~icons/custom/logo-fill')['default'];
    IconCustomNetworkError: typeof import('~icons/custom/network-error')['default'];
    IconGridiconsFullscreen: typeof import('~icons/gridicons/fullscreen')['default'];
    IconGridiconsFullscreenExit: typeof import('~icons/gridicons/fullscreen-exit')['default'];
    IconIcOutlineCheck: typeof import('~icons/ic/outline-check')['default'];
    IconLineMdMenuFoldLeft: typeof import('~icons/line-md/menu-fold-left')['default'];
    IconLineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default'];
    IconMdiArrowDownThin: typeof import('~icons/mdi/arrow-down-thin')['default'];
    IconMdiArrowUpThin: typeof import('~icons/mdi/arrow-up-thin')['default'];
    IconMdiClose: typeof import('~icons/mdi/close')['default'];
    IconMdiGithub: typeof import('~icons/mdi/github')['default'];
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default'];
    IconMdiPin: typeof import('~icons/mdi/pin')['default'];
    IconMdiPinOff: typeof import('~icons/mdi/pin-off')['default'];
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default'];
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default'];
    IconPhCaretDoubleLeftBold: typeof import('~icons/ph/caret-double-left-bold')['default'];
    IconPhCaretDoubleRightBold: typeof import('~icons/ph/caret-double-right-bold')['default'];
    IconSelect: typeof import('./src/components/custom/IconSelect.vue')['default'];
    IconUilSearch: typeof import('~icons/uil/search')['default'];
    ImageVerify: typeof import('./src/components/custom/ImageVerify.vue')['default'];
    LoadingEmptyWrapper: typeof import('./src/components/business/LoadingEmptyWrapper.vue')['default'];
    LoginAgreement: typeof import('./src/components/business/LoginAgreement.vue')['default'];
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default'];
    SystemLogo: typeof import('./src/components/common/SystemLogo.vue')['default'];
    WebSiteLink: typeof import('./src/components/custom/WebSiteLink.vue')['default'];
  }
}

export {};
