packages:
  - 'packages/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  typescript: npm:typescript-native-bridge@latest
overrides:
  vite: 'catalog:'
  typescript: 'catalog:'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: false
  vue-demi: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@iconify/json@2.2.541'
  - '@tauri-apps/api@2.12.2'
