packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  es5-ext: false
  esbuild: false
  simple-git-hooks: true
  typeit: false
  unrs-resolver: false
  vue-demi: false
