export enum EnumRoutePath {
  'root' = '/',
  'login' = '/login',
  'not-found' = '/404',
  'no-permission' = '/403',
  'service-error' = '/500',
  'reload' = '/reload',
  // 自定义路由
  'dashboard' = '/dashboard',
  'dashboard_analysis' = '/dashboard/analysis',
  'dashboard_workbench' = '/dashboard/workbench',
  'document' = '/document',
  'document_vue' = '/document/vue',
  'document_vite' = '/document/vite',
  'document_naive' = '/document/naive',
  'component' = '/component',
  'component_map' = '/component/map',
  'component_video' = '/component/video',
  'component_editor' = '/component/editor',
  'component_editor_quill' = '/component/editor/quill',
  'component_editor_markdown' = '/component/editor/markdown',
  'component_swiper' = '/component/swiper',
  'multi-menu' = '/multi-menu',
  'multi-menu_first' = '/multi-menu/first',
  'multi-menu_first_second' = '/multi-menu/first/second',
  'exception' = '/exception',
  'exception_403' = '/exception/403',
  'exception_404' = '/exception/404',
  'exception_500' = '/exception/500',
  'about' = '/about'
}

export enum EnumRouteTitle {
  'root' = 'root',
  'login' = '登录',
  'not-found' = '未找到',
  'no-permission' = '无权限',
  'service-error' = '服务器错误',
  'reload' = '重载',
  // 自定义路由
  'dashboard' = '仪表盘',
  'dashboard_analysis' = '分析页',
  'dashboard_workbench' = '工作台',
  'document' = '文档',
  'document_vue' = 'vue文档',
  'document_vite' = 'vite文档',
  'document_naive' = 'naive文档',
  'component' = '组件插件',
  'component_map' = '地图插件',
  'component_video' = '视频插件',
  'component_editor' = '编辑器',
  'component_editor_quill' = '富文本编辑器',
  'component_editor_markdown' = 'markdown编辑器',
  'component_swiper' = 'Swiper插件',
  'multi-menu' = '多级菜单',
  'multi-menu_first' = '一级菜单',
  'multi-menu_first_second' = '二级菜单',
  'exception' = '异常页',
  'exception_403' = '异常页-403',
  'exception_404' = '异常页-404',
  'exception_500' = '异常页-500',
  'about' = '关于'
}
