/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  favorite: () => import("@/views/favorite/index.vue"),
  home: () => import("@/views/home/index.vue"),
  pan: () => import("@/views/pan/index.vue"),
  recently: () => import("@/views/recently/index.vue"),
  recycle: () => import("@/views/recycle/index.vue"),
  share_group: () => import("@/views/share/group/index.vue"),
  share_me: () => import("@/views/share/me/index.vue"),
  share_public: () => import("@/views/share/public/index.vue"),
};
