/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>;
    "403": RouteRecordInfo<"403", "/403", Record<never, never>, Record<never, never>>;
    "404": RouteRecordInfo<"404", "/404", Record<never, never>, Record<never, never>>;
    "500": RouteRecordInfo<"500", "/500", Record<never, never>, Record<never, never>>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "IframeUrl": RouteRecordInfo<"IframeUrl", "/iframe/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "Login": RouteRecordInfo<"Login", "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?", { module?: ParamValueZeroOrOne<true> }, { module?: ParamValueZeroOrOne<false> }>;
    "ManageMenu": RouteRecordInfo<"ManageMenu", "/manage/menu", Record<never, never>, Record<never, never>>;
    "ManageRole": RouteRecordInfo<"ManageRole", "/manage/role", Record<never, never>, Record<never, never>>;
    "ManageRoute": RouteRecordInfo<"ManageRoute", "/manage/route", Record<never, never>, Record<never, never>>;
    "ManageUser": RouteRecordInfo<"ManageUser", "/manage/user", Record<never, never>, Record<never, never>>;
    "Wip": RouteRecordInfo<"Wip", "/wip", Record<never, never>, Record<never, never>>
  }
}
